SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
BACKGROUND_COLOR = "white"

PLAYER_COLOR = "blue"
TARGET_COLOR = "red"

PLAYER_WIDTH = 20
PLAYER_HEIGHT = 30
TARGET_RADIUS = 15

PLAYER_START_X = 50
PLAYER_START_Y = 50
PLAYER_SPEED = 4

FRAME_DELAY = 16
WINDOW_TITLE = "Дістанься до цілі"
