WINDOW_TITLE = "Crystal Sprint"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
BACKGROUND_COLOR = "#0b1021"

PLAYER_COLOR = "#49d6ff"
ENEMY_COLOR = "#ff5d73"
CRYSTAL_COLOR = "#ffd166"
PROJECTILE_COLOR = "#ffffff"
TEXT_COLOR = "#f5f7ff"
ACCENT_COLOR = "#7cffb5"

PLAYER_SIZE = 18
PLAYER_SPEED = 5
PLAYER_LIVES = 3

ENEMY_SIZE = 16
ENEMY_BASE_SPEED = 1.4
ENEMY_SPAWN_FRAMES = 70

CRYSTAL_SIZE = 12
CRYSTAL_SPAWN_FRAMES = 180

PROJECTILE_SIZE = 6
PROJECTILE_SPEED = 9

WIN_SCORE = 20
FRAME_DELAY = 16
