WINDOW_TITLE = "Гра JUMP!"

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 400
BACKGROUND_COLOR = "white"

PADDLE_COLOR = "blue"
BALL_COLOR = "red"

PADDLE_WIDTH = 100
PADDLE_HEIGHT = 12
PADDLE_START_X = 200
PADDLE_START_Y = 300
PADDLE_SPEED = 6

BALL_SIZE = 22
BALL_START_X = 245
BALL_START_Y = 100
BALL_SPEED_Y = 3

FRAME_DELAY = 16
